MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
  #TRAIN: ("D:/mystudy/data/ssd/VOCtrainval_06-Nov-2007/VOCdevkit", "D:/mystudy/data/ssd/VOCtrainval_11-May-2012/VOCdevkit")
  #TEST: ("D:/mystudy/data/ssd/VOCtest_06-Nov-2007", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 8
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_voc0712'